name: Github Pages Deploy

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.20.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        working-directory: ./gitactions-demo
        run: npm install && npm run build && cp dist/git-actions/index.html dist/git-actions/404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-deploy # The branch the action should deploy to.
          folder: gitactions-demo/dist/git-actions # The folder the action should deploy.
